### PR TITLE
Make "use other case" translatable

### PR DESCRIPTION
**Pull request by RoinujNosde**
I don't know if this works :)

PS.: Replace mentally "user other case" by "use other case"

### CODE REVIEW

**Comment by ljacqu** [comment]
I'll squash the commits this evening (it will still be your name ^^) and fix whatever test is failing. It looks good!

**Comment by RoinujNosde** [comment]
MessageKey.java - line 130: It has to be a comma in the end, right?

**Comment by RoinujNosde** [comment]
Closed by accident... :/

**Comment by ljacqu** [comment]
Thanks for the PR, your changes and some adjustments have been added via PR #110. Please don't put every single file in a separate commit.. :P

**Comment by RoinujNosde** [comment]
How i make only one commit? :/

**Pull request closed without merging**
