### PR TITLE
IPB4 Support

### PR DESCRIPTION
**Pull request by DNx5**
Add IPB4 support to AuthMe

### CODE REVIEW

**Comment by DNx5** [comment]
Took 20s to run IPB4 test, weird.
#483

**Comment by sgdc3** [comment]
lol why?

**Comment by DNx5** [comment]
idk, probably the salt make it slow

**Comment by ljacqu** [comment]
Excellent work. Only the addition to `HashAlgorithm` is missing ;)

**Comment by DNx5** [comment]
lol, i forget that.

**Pull request merged**
