### PR TITLE
Updated strings, Revert Infringements and invalids

### PR DESCRIPTION
**Pull request by lifehome**
Oh dear why would some kiddle removes my remark, also the original commit is invalid due to the string is not properly translated in zh_HK, while it is just **copied** from zhcn.

Prior to my current commit, new strings and the modified ones are being non-user-friendly to players, and shows machine translated clues. Such commits is not acceptable.

### CODE REVIEW

**Comment by lifehome** [comment]
Commit that removes all remarks and user-friendly strings, replaced by some machine translated strings:  
Xephi/AuthMeReloaded@048bfd2a6c340d2dff619e713ac56747b5adb1ea  

Commit that replaced translated placeholder, which is complete unnecessary and non-sense
Xephi/AuthMeReloaded@c48b7c23276485fd37d608ca836436705d8c103a

**Comment by sgdc3** [comment]
@lifehome It's ok but please don't translate placeholders. (if you change them they wouldn't work!)

**Comment by ljacqu** [comment]
> Please don't make me to enforce a DMCA takedown just because of some kiddle removes my remark.

@lifehome needs to take a few deep breaths

**Comment by ljacqu** [comment]
As sgdc3 mentioned, kindly don't replace placeholder tags as they will be replaced with content when shown to the user.

For your changes to be accepted, please fix the following validation errors:
```
Validation errors in /messages/messages_zhhk.yml:
- Message with key 'max_reg' missing tags: %max_acc, %reg_count, %reg_names
- Message with key 'usage_captcha' missing tag: <theCaptcha>
- Message with key 'wrong_captcha' missing tag: THE_CAPTCHA
```

I'd also like to ask you not to submit changes with threats in the commit messages. Your _entire_ file was replaced by someone else's. I understand that this is upsetting for you but this really gives you no ground at all for a DMCA takedown.

With that said, your contribution of translation message is greatly appreciated. Especially since you know your way around Github, this makes our life quite easier :)

**Comment by DNx5** [comment]
I don't understand zh_HK, but the file is changed because
#521

**Comment by lifehome** [comment]
Oh wow, amazing. I'll deal with that on that issue

**Comment by lifehome** [comment]
Okay so I have "communicated" with that #521 guy, whom a person I knew a long time ago.

Situation now is: zh_CN is overrided with my old translated, outdated and invalid to zh_CN lingual;  
zh_HK is invalid due to the new translation is just Google Translate and _copied_ from the old zh_CN;  
zh_TW is invalid and _outdated_, I have contacting the Taiwan translator and preparing the new strings for PR.

Explaination to the zh_HK file:  
The Guy I have talked to, did translated from English to zh_HK, however, and, as-is he admitted his English level is not quite good, thus he only aims to literally translate the "string" itself, but instead not to understand "what the string means" for.  
My previous version are tested through from Minecraft version 1.5 to 1.8.8, where I have tested if the fonts and symbols are compatible with English(Default Language, as partial players in HK don't change the language), and Traditional Chinese(Some english/chinese symbol will crash and collide in different language, causing readability issue). I have also specifically added `'&8[&6用戶系統&8]` to indicate which plugin the string is showing from, to assist player and server owner, in case of any problems caused.  
I have to admit that it is my fault that I commited directly the version of my server, where I symlinked the git repo to my server's plugin folder, but didn't aware of the server-name issue. Also, the string in zh_HK is not 100% translated as-is what they means in English, the reason to do so is because of some players wanted to focus on the gaming experiences, instead of annoying message which causing them time to understand, therefore I have added some interjection and emotion at the end of the sentences, expressing a kind and nice attitude to the player, instead of some machine-like response.

Lastly, I agrees @ljacqu `@lifehome needs to take a few deep breaths`, which I do need some;  
I will propose another PR, which will contain all `zh` translation, and updates the TODO strings.

Please let me know if I need to improve in some other aspects, such as EQ :satisfied:

**Comment by ljacqu** [comment]
Thanks a lot for the detailed analysis and for communicating with the other person. Sorry for the confusion when the file was overridden. We appreciate your contributions and look forward to your PR.

**Comment by Saren-Arterius** [comment]
Seriously please just revert https://github.com/AuthMe-Team/AuthMeReloaded/commit/048bfd2a6c340d2dff619e713ac56747b5adb1ea. The new translate does not make any sense at all.

**Comment by AnthonyTsang** [comment]
As a Hongkonger, I can confirm that, this PR is a lot better than #521 in zh_HK. #521 is rough and not making much sense. 

A bit background of the language. zh_HK is in traditional Chinese as zh_TW. zh_CN is in simplified Chinese. Most Chinese readers can read both Chinese languages, but the wordings, phrases and culture may have huge differed. Therefore, by simply copy zh_CN to Google Translate, you will have a grammatically correct traditional Chinese without any localization on zh_HK. 

This PR is much similar to what I write natively. I believe it is much easier to read by most Chinese reader living in Hong Kong.

**Pull request closed without merging**
