### PR TITLE
432 dependency injection

### PR DESCRIPTION
**Pull request by ljacqu**
Still a work in progress, but this PR constitutes the foundation of how I'd like to solve #432. This takes care of the huge constructors some of the services have amassed over time and gets rid of confusion about the instantiation order (causing bugs such as #667).

Re-inventing the wheel is never good but this is a lot lighter than Guice, and we can fine-tune it to _our_ needs since it's our in-house injector. It's unit tested with a coverage of 93% currently, and you can see in the tests folder that I set up a whole array of test classes to check different types of situations.

This not only helps us avoid clumsy initializations, but in the future we can create an interface (`Reloadable`) and have the service initializer call a method on such implementors --> central reloading for /authme reload without having to list them all :)

I'd love for reviews, comments, and ideas.

### CODE REVIEW

**Comment by ljacqu** [comment]
@sgdc3 @games647 @Xephi @DNx5
Commit 9af5963 shows how services can be injected into the commands. It literally just requires adding a field with `@Inject`. Same for testing, if you look at the changes in the test classes you'll see that a lot of linking logic can be removed.

I would like to ask you to have a look at it and merge it if you approve the changes, or voice your concerns and I'll be make to address them. What's still open on my side is to fix the tool tasks. A continuation of this once it's on master will be to implement reloading on the services where it makes sense, which will be very easy thanks to the injection that keeps track of all our services.

**Comment by games647** [comment]
:+1:

**Comment by sgdc3** [comment]
amazing :D

**Comment by ljacqu** [comment]
Thanks for the support -- I was a little worried how well this would be received since this introduces fundamental changes into the project setup. I think this is the best solution for us, though, after the Wrapper and the services I think this might be it... :P 
As I said, fixing the tool tasks is still on my side and I'll also write a Wiki page about the injector's setup. This way we have some documentation about it.

**Pull request merged**
