### PR TITLE
Remove gamemode and flying switching

### PR DESCRIPTION
**Pull request by games647**
This pr removes the saving and restoring of gamemodes and flying states in order to fix inventory wipes and missing flying permissions.

This pr is open for discussion and testing.

- [x] Inventory is protected if the player isn't logged in.
- [x] Gamemodes keeps the same
- [x] Inventory cannot be changed until the player log in
- [x] Flying state keeps the same
- [x] Inventory is correctly separated by MultiInv if the gamemode changes.

### CODE REVIEW

**Comment by ljacqu** [comment]
From a technical point of view this seems good. This solution is probably based on the assumption that our listeners catch all sorts of events and cancel them when the player is not logged in?

**Comment by games647** [comment]
>This solution is probably based on the assumption that our listeners catch all sorts of events and cancel them when the player is not logged in?

yes

**Comment by ljacqu** [comment]
I think your simplifying the entire handling is the correct approach, since it seems like no one really has an overview anymore where the gamemode is being manipulated. Furthermore, I can imagine that various plugins handle the inventory in different ways upon gamemode change, causing the inventory to be cleared if we don't behave as the plugin expects.

Of course assuming that our listeners are _flawless_ is arguably risky, but we _are_ meant to catch everything, and getting rid of strange gamemode and inventory problems definitely outweighs a moderately "risky assumption." It would be interesting to know if someone with more experience around Minecraft plugins has any concerns.

**Comment by games647** [comment]
>Of course assuming that our listeners are flawless is arguably risky, but we are meant to catch everything,

It's always risky, but if for example we fail to catch command events, the server would be vulnerable **too**.

**Comment by games647** [comment]
Then I think it's ready to be merged, isn't it?

**Comment by sgdc3** [comment]
JUST DO IT!

**Comment by games647** [comment]
I asked multiple times if we really need this feature.

**Pull request merged**
