### PR TITLE
Periodic Italian Update

### PR DESCRIPTION
**Pull request by Maxetto**
Still keeping it updated :wink:

### CODE REVIEW

**Comment by sgdc3** [comment]
whoops wrong button xD

**Comment by Maxetto** [comment]
@sgdc3 Did I? Besides Twitter and GitHub, I don't think we never been friends on a social network.

**Comment by sgdc3** [comment]
Skype, and (Telegram? I don't remember)

**Comment by Maxetto** [comment]
Not using neither of those 2. :/

**Comment by Maxetto** [comment]
Damn! I've not done it in time for BETA 3 :/

**Comment by sgdc3** [comment]
There is still beta4 before release ;)

**Pull request merged**
