### PR TITLE
Unit tests and simple refactorings

### PR DESCRIPTION
**Pull request by ljacqu**
More test additions and some easy refactoring as I get familiar with the code.

### CODE REVIEW

**Comment by timvisee** [comment]
Great additions! Nice work!

**Comment by ljacqu** [comment]
Thanks :) Sorry for the conflict; I think that's my fault (not properly separating my two pull requests). I'm working on resolving it.

**Comment by timvisee** [comment]
@ljacqu 
Nevermind the conflict! It might even be caused by me, because I did quite a few commits in the last few hours.

I'm trying to manually resolve it now.

**Comment by ljacqu** [comment]
@timvisee Oh, thanks for your time in that case!

**Comment by timvisee** [comment]
@ljacqu Weird, the manual merge method doesn't seem to be working quite well. Can you maybe create a new pull request, to solve the conflicts?

**Comment by ljacqu** [comment]
If it's OK with you, I can cherry pick the commits in this PR and commit them to master directly. That would be the easiest way to resolve it.

**Comment by timvisee** [comment]
@ljacqu Sure, go ahead. I hope the cherry picked commits don't cause any conflicts, but we'll find out soon enough.

**Comment by ljacqu** [comment]
Thanks!

**Pull request closed without merging**
