### PR TITLE
Discussion/Tentative: Use Guice

### PR DESCRIPTION
**Pull request by ljacqu**
To the AuthMe dev team—@sgdc3 @DNx5 @games647 @timvisee @NoChanceSD

Guice is a framework by Google that takes care of dependency injection for us. This means we can simply slap `@Inject` annotations on constructors or fields and the required fields will be added by Guice automatically.

This means we don't have to write the "glue" code on start up to create all classes in the right order... Guice figures this out for us. I see the following pro's:

- Easier to handle many different service / utility classes, such as in AuthMe
- Hide "intermediate" classes we don't care about (we no longer need to instantiate things like `HelpProvider`: some classes need it but on a higher level we really don't care about it)
- Facilitates unit testing

It has the following cons:
- Introduces a new dependency, makes us dependent on a library for quite crucial operations
- Adds 0.4 MB to the JAR
- Might hide some instantiation flow we could potentially care about
- No IDE support? The `@Inject` fields show me a warning that they are never instantiated and I can't seem to find a plugin that takes care of this (although my work laptop does recognize them! Need to find out what plugin it has...)

---

If we decide to go with this we could later on make the services implement various interfaces, such as `Reloadable`. For `/authme reload` we can then get all `Reloadable` services from Guice without listing each service in the code itself. Easy to extend.

I personally think that Guice could make our life easier, especially as we refactor even more and deal less and less with those `getInstance()` type of services (as I have been working to reduce). Guice also has a graphing module to show which services depend on each other—very cool.

At the same time, I feel that this makes us dependent on a library at a very sensible place: instantiating all of our services. If we use Guice for a while I reckon it would be hard to go back. Comparatively, it's not that difficult to encapsulate all the logic for creating services into some class called in `onEnable()`.

I'm kind of undecided... but I tend to want to adopt Guice in our project, notably because some of my doubts are alleviated by the fact that Guice is a stable product by no less than _Google_.

### CODE REVIEW

**Comment by sgdc3** [comment]
It seems interesting...

**Comment by games647** [comment]
I really love Guice, but I think it's a bad decision to add another dependency. In my opinion the server should add such dependencies like in the case of Sponge.

**Comment by CryLegend** [comment]
AuthMe = small-scale project.
+ Guice does not encourage contributions (PR) because it's not easy to
understand how it works.

**Comment by ljacqu** [comment]
Then it's settled—no Guice. It was a fun experiment to do but I agree it should stay that :)

**Comment by ljacqu** [comment]
Also @CryLegend is my memory bad or is this like the first comment you've made on this project?

**Comment by Xephi** [comment]
Guice is a good idea to help developpement of a project, but not in a case of a bukkit plugin, cause it force us to dev through a guideline community may don't expect :/

**Comment by CryLegend** [comment]
@ljacqu It looks like

**Pull request closed without merging**
