### PR TITLE
Move the converter command [WIP]

### PR DESCRIPTION
**Pull request by sgdc3**
[x] check if the parent command has been added correctrly
[x] Fix test

### CODE REVIEW

**Comment by sgdc3** [comment]
@ljacqu

**Comment by ljacqu** [comment]
Is the mention for me to explain why the test is failing? :P

**Comment by sgdc3** [comment]
yeah, also to check if i forgot something ;P

**Comment by ljacqu** [comment]
I was going to mention the plugin.yml so good job on that :P

In CommandInitializer:
```java
        // Rename me and add me to the other AUTHME_BASE commands
        CommandDescription CONVERTER_BASE = CommandDescription.builder()
            .parent(AUTHME_BASE)
   ...
Set<CommandDescription> baseCommands = ImmutableSet.of(
            AUTHME_BASE,
            ...,
            CONVERTER_BASE); // <-- remove me
```
I think the test are failing because of that (still in Set of base commands)

**Comment by sgdc3** [comment]
@ljacqu I need to go now, if you want do it, i'll check it later to finally understand how the command structure works xD

**Comment by ljacqu** [comment]
@sgdc3 I think it's a good exercise to understand the command handling and it's not time-sensitive, so it's fine if it takes some time ^^ I'm a comment away for questions so hopefully that's sufficient :3

**Comment by ljacqu** [comment]
@sgdc3 How's it going with this?

**Comment by sgdc3** [comment]
@ljacqu I had no free time these days :( sorry. I'll try to do this now ;)

**Pull request merged**
