### PR TITLE
Updated messages_br.yml.

### PR DESCRIPTION
**Pull request by nathampa0909**
I put accents and I did a new translation better than old.

### CODE REVIEW

**Comment by ljacqu** [comment]
Thanks for the pull request – only issue detected by our _verifyMessages_ tool task is:

>  Missing tag '&lt;theCaptcha>' in entry with key 'usage_captcha'

We can fix that manually after accepting this pull request. If you agree @sgdc3, you can merge it. :)

**Comment by nathampa0909** [comment]
@ljacqu You are welcome! Thanks for attention! And sorry for missing tag!

**Comment by games647** [comment]
>only issue detected by our verifyMessages tool task is:

@ljacqu Do you checked manually? It would be great if this is included in the travis status checking.

**Comment by ljacqu** [comment]
@games647 Semi-manually — if you run the ToolsRunner in src/tools/ and select `verifyMessages` you can check the files. Currently too many errors in our messages file to have it as a unit test, but that would be a nice idea for the future :)

**Comment by games647** [comment]
@ljacqu Thanks

**Comment by nathampa0909** [comment]
I used original message file of AuthMe, I forgot only the <theCaptcha>.

**Comment by ljacqu** [comment]
Yeah no worries, it might even be that the replacement was changed later on or something ^^

**Pull request merged**
