### PR TITLE
[Feedback required] Make the purge progress run more balanced (Fixes #696 and #676)

### PR DESCRIPTION
**Pull request by games647**
This PR lets the purge process run more balanced. 

- Shows the progress each second
- Replaced a couple of lists to hashsets for faster comparisons (hash vs string equalsIgnore)
- Purge process will only lookup the the offline players once
- Run each tick in order to prevent lag spikes if we run in only each second

### CODE REVIEW

**Comment by ljacqu** [comment]
I haven't executed the code but looked at the changes. +1 for putting purge things into a dedicated task and +1 for removing some code duplication (the setting checks). Changing to a Set was a good call, too.

Was it a conscious decision to loop over all OfflinePlayers and to check against the purged list? (As opposed to iterating over the purged list and mapping the names to an OfflinePlayer instance.)

PurgeBannedPlayersCommand returns a List of OfflinePlayer, their names are passed to the PurgeTask, which then loads all OfflinePlayers.

**Comment by games647** [comment]
Thanks for the feedback

>Was it a conscious decision to loop over all OfflinePlayers and to check against the purged list? (As opposed to iterating over the purged list and mapping the names to an OfflinePlayer instance.)

I thought about that too. In the current implementation it's like that. I'm assuming that it was implemented like that in order to perform case-insensitive lookups. As far as I know getOfflinePlayer(String) is performing a case-sensitive lookup. 

For example:

A player chose a name with a upper-case letter in it. We would save then save the lowercased name to the database, but I assume that the server associates the player dat (because of UUIDs?) file only to the exact same username. 

Isn't this the reason we implemented the config option preventOtherCase.

>PurgeBannedPlayersCommand returns a List of OfflinePlayer, their names are passed to the PurgeTask, which then loads all OfflinePlayers.

You are right. That's pretty stupid. It was like that before, but it's better if we change that..

**Comment by ljacqu** [comment]
Thanks for doing this, that's quite a challenging problem that you're tackling.

> Isn't this the reason we implemented the config option preventOtherCase.
Yes, in offline mode the UUIDs are case-sensitive, i.e. if I join with "bobby" I will get another UUID than with "Bobby."

**Comment by games647** [comment]
I made some changes. 

To the purgebanned thing:
It will still hit the file system twice due two calls to the method getName() (one in the command and one in the task), but I don't think it's necessary to change it. Isn't it better to keep it like it's currently implemented instead of special casing it?

I removed the duplicate call to getOfflinePlayers() so it should be optimized enough or what do you think?

**Comment by games647** [comment]
BTW: also fixes #676

**Comment by rErEaT** [comment]
how does it fix that?
what permission or ?

**Comment by games647** [comment]
This will purge the permissions too if you want to run the purge command.

**Comment by rErEaT** [comment]
from permissionsex file?

**Comment by games647** [comment]
yes

**Comment by rErEaT** [comment]
Okay, but I need a permission which can bypass from the purge

**Comment by ljacqu** [comment]
Could only look at it quickly today, but looks great @games647 :smile: I'll check out your branch tomorrow to have a closer look

**Comment by games647** [comment]
@ljacqu Thanks a lot for looking over it.

**Comment by ljacqu** [comment]
:+1: @games647 Again, haven't tried to actually run it but I stepped through the code. Looks great, thanks for fixing my remarks.

For me it's fine to merge. Just please don't forget you have some commented out code in PurgeTask:
```java
        //this is commented out because I assume all players in the database already have an lowercase name
//        toPurge = new HashSet<>(purged.size());
        //make a new list with lowercase names to make the username test based on a hash
//        for (String username : purged) {
//            toPurge.add(username.toLowerCase());
//        }
```
---

One improvement we can do sometime in the future is have some sort of PurgeService that keeps track of autoPurging and so forth. That way we don't need AuthMe main class to keep track of it with an autoPurging field. But that's "sometime in the future" :smile:

**Comment by sgdc3** [comment]
Merged

**Pull request merged**
